variables:
  PROJECTNAME: libsqpSpiSlaveLinux

stages:
  - package

package-spiSlaveLinux:
  image: registry.swissqprint.com/sqp/devops/runner/conan:0.9
  stage: package
  tags:
    - docker
    - linux
    - x86_64
  only:
    - tags
  script:
    - conan remove $PROJECTNAME -f
    - conan create . sqp/release --update -pr linux64_x_armv7hf-none-eabi_gcc9 -s build_type=Release
    - conan upload $PROJECTNAME --all -r=inhouse -c



